### ISSUE TITLE
Supabase?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#93]
Been watching the progress on Supabase for a while but not opened an issue! 🤦‍♂️ 
https://github.com/supabase/supabase

https://supabase.com/
![image](https://user-images.githubusercontent.com/194400/170020189-c20a0c5e-b792-45d6-b776-822d5bb8d696.png)

**Comment by nelsonic** [comment]
Multiplayer: https://supabase.com/blog/supabase-realtime-multiplayer-general-availability
Via: https://news.ycombinator.com/item?id=32510405

**Comment by nelsonic** [comment]
#073 Elixir at Supabase with Paul Copplestone November 16, 2021
https://thinkingelixir.com/podcast-episodes/073-elixir-at-supabase-with-paul-copplestone/

**Comment by nelsonic** [comment]
@SimonLab this: https://supabase.com/docs/guides/getting-started/tutorials/with-flutter ?

**Comment by nelsonic** [comment]
@LuchoTurtle please speed run this: https://supabase.com/docs/guides/getting-started/tutorials/with-flutter
and drop a comment here with your experience. 🙏

**Comment by nelsonic** [comment]
@LuchoTurtle https://github.com/dwyl/supabase-flutter-demo/issues/1 looks promising. 🤞 
Please do your best to follow instructions though. 🙏 
No comment. No work done. I'm left scratching my head. 🤷‍♂️ 
> **Note**: not saying you didn't ***`do`*** the work. Just that I cannot _see_ it ... 😞

**Comment by nelsonic** [comment]
Currently doing a Deep Dive into the https://github.com/supabase/supabase `code`. 👀 👨‍💻 ⏳

**Comment by nelsonic** [comment]
https://supabase.com/pricing
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/194400/215250593-a88be42a-063e-4dd1-b1b9-6d07593dfbfb.png">

Depending on the availability/reliability, **`$25/month`** is either _cheap_ or expensive ... 💭 
If you look at the size of the DB you get to to host **`8Gb`** is not very much ...
But it's enough for an MVP. 
**`5GB`** file uploads / month and **`100GB`** of File Storage is also not a lot ... 

![image](https://user-images.githubusercontent.com/194400/215250723-95a3bb50-b2c8-4b4e-bb36-4271769d7f5e.png)

OK, this pricing has a healthy margin over their cloud/infra provider.
But I don't find it _offensive_ like some other `PaaS` providers.

**Comment by nelsonic** [comment]
When you _first_ look at this repo: https://github.com/supabase/supabase

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/194400/215264217-1879e941-7390-4c6b-9eac-99a6f493003a.png">

What is your intuition as to what the "entry point" for understanding the `code` is ...? 🤷‍♂️ 
if you were to try and _run_ `Supabase` on your `localhost`: 
https://github.com/supabase/supabase/blob/master/DEVELOPERS.md#local-development

<img width="1312" alt="supabase-no-postgres" src="https://user-images.githubusercontent.com/194400/215270764-e3aae83f-47bd-4012-b989-5e3686acfc67.png">

No mention of `Postgres` in the dev guide ... 🤷‍♂️ 
But in their Architecture section, `Postgres` is the data store:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/194400/215271179-ea9b35c8-3ef4-47cf-b12a-3ae7ec4fd083.png">

So _where_ is the data being stored on `localhost`? 🔍 

And if you wanted to host it yourself to have _control_ over the data, 
https://supabase.com/docs/guides/self-hosting
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/194400/215264391-3ec96d84-2525-4c5d-92d1-154901d1c728.png">

There are quite a few moving parts ...

**Comment by nelsonic** [comment]
The questions I want to answer before _considering_ using `Supabase` for our `App` are:
1. What is the _average_ round trip response time for an `HTTP` Request
2. How efficient is the websocket/realtime socket, does it send large amounts of data or just the diff?
3. Does it have ***`presence`*** built-in so we can see "Who's online"?

> Looks like it's just a `Phoenix 1.6.12` server: https://github.com/supabase/realtime/blob/f89117850839af76ef0648d7e8bfde6450515745/mix.exs#L44
So `presence` is available. 💭 

Having watched all the _official_ `Supabase` Auth videos: 
https://supabase.com/docs/guides/auth/overview

My conclusion is that what they have built is _good_...
But _definitely_ more complex than it _needs_ to be. 
And I've spotted _several_ areas that we can _substantially_ improve.

**Comment by nelsonic** [comment]
My _next_ question is: how does the `Supabase` `Flutter` `SDK` work when the person/device is ***offline***? 
Reading: https://github.com/supabase/supabase/discussions/357 I conclude that it's not implemented.
So ... we would need to _wrap_ the `SDK` to check for connectivity, save the `item`, `tags` & `timer` data _offline_ and then create our own conflict resolution & sync code. 💭 

One of the non-negotiables we _must_ have in our **`Native Mobile App`** is **Offline _First_**.

**Comment by nelsonic** [comment]
How are table definitions and schema migrations version controlled in `Supabase`? 🤷‍♂️ 
My reading of https://supabase.com/docs/guides/database/tables 
Is that schemas are created in the Dashboard (Web UI): Watch: https://youtu.be/TKwF3IGij5c
<img width="939" alt="image" src="https://user-images.githubusercontent.com/194400/215304823-eb53b51a-9596-471b-ac41-5a872fa937bb.png">

# 🤷‍♂️ 

https://www.google.com/search?q=supabase+schema+migration
How to Manage Database Migration Using Supabase CLI - SupabaseTips: https://youtu.be/Kx5nHBmIxyQ
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/194400/215305138-aba103dd-c478-48ac-8c34-8ebb0afbe9af.png">

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/194400/215305275-54b500d8-0374-4155-92d9-b5e3be392f32.png">

The top comment for this video is the following question:
<img width="628" alt="image" src="https://user-images.githubusercontent.com/194400/215305287-37023589-633c-4eff-b775-12f6f3c05d85.png">

So ... basically if you use the Supabase cloud service for building your App you cannot connect to the DB from your `localhost` and run the schema diff in order to store the schema in your project on GitHub. 
So ... version control of schema is solved. 

Supabase is looks _great_ for a _single_ dev working by themself but the "***Team***" **workflow** is _not_ well-defined at all.

I _still_ think this is _immensely_ promising! 
I just think that manually defining schema in a Web UI and not having a clear migration path from one instance to another e.g `Dev` -> `CI` -> `Staging` / `Review Apps` -> `Production` 
Is a bit of a non-starter for people building an `App` as a ***Team***. 
The opportunity for **conflicts** and the resulting time-wasting is not even _slightly_ appealing to me. 😕

**Comment by nelsonic** [comment]
Reading: https://www.slip.so/tutorials/database-migrations-in-supabase-with-migra

<img width="794" alt="image" src="https://user-images.githubusercontent.com/194400/215305722-b581a2fe-52ff-40ae-919b-24ddbfef913f.png">

https://databaseci.com/docs/migra
<img width="853" alt="image" src="https://user-images.githubusercontent.com/194400/215305736-0b1901c9-031e-47e7-b790-63a9e3c9b599.png">

Indeed ... 🙄 
Maybe I shouldn't be doing this at 04:55 on a Sunday during the traditional "maintenance window" ... 💭

**Comment by nelsonic** [comment]
Quick Google and we find: https://github.com/djrobstep/migra
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/194400/215305889-6aa73531-bbc5-4655-b892-97b4e6fb1aaa.png">

Project URL matches the one above that is "Down for maintenance" so looks like we're in the right place. 👌 

Docs point to: https://databaseci.com/docs/migra 
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/194400/215305952-3d6b5de8-8fe2-4563-8a15-e121e13611e6.png">

Which as we established above is "Down for maintenance". ...

Their tutorial requires you to run a `docker` container to use `migra` ... 

Last commit [da6671a](https://github.com/djrobstep/migra/commit/da6671acae0b4acebdec804ae25a0c65cf8561c2) on [Sep 18, 2022](https://github.com/djrobstep/migra/commit/da6671acae0b4acebdec804ae25a0c65cf8561c2) ... ⏳ 

Apparently the docs site has been down for at _least_ 2 weeks: https://github.com/djrobstep/migra/issues/225

**Comment by nelsonic** [comment]
Official discussion: https://github.com/supabase/supabase/discussions/134 marked as "Answer":
<img width="918" alt="image" src="https://user-images.githubusercontent.com/194400/215306887-97733747-5e60-4ef2-8b68-6e5449f9d997.png">

Yes, it's `Postgres` under-the-hood. But "go use one of the available tools" isn't a great answer ... 🤷‍♂️ 
I need an end-to-end example of how to do this `before` I `commit` resources to pursing this route. 💭

**Comment by nelsonic** [comment]
Had a conversation with @SimonLab on Standup this morning regarding `Supabase`.
I _agree_ that it _looks_ good, at least _superficially_. They're building an open source clone of `Firebase`

I did a _deep dive_ into the code and watched _all_ the (relevant) videos on their channel on YT: https://www.youtube.com/@Supabase/videos
I'm still optimistic about using it. 
I just don't think we _need_ it it for our `MVP` or even for our `App`. 
`Supabase` is a _good_ scaffolding for people who _don't_ have `Phoenix`.
The key selling point is the "Realtime" sync of data: https://github.com/supabase/realtime
And that is just ***`Phoenix`***!! Which is good "_validation_" of the Tech Stack we're _already_ using.
the `Supabase` team dont' _appear_ to care about running the tests for the `realtime` app on GitHub CI:
[github.com/supabase/realtime/tree/main/.github/workflows](https://github.com/supabase/realtime/tree/4c0c3421b2a9e1b6d2082842832b2db8654eeb0b/.github/workflows)
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/194400/215828688-93ae12e8-655e-48ae-acb8-c8be132e6909.png">

All of these `CI` workflows are related to deployment. None are testing that the _features_ work as expected.
I tried to run the project on `localhost` "as is" and it simply doesn't run: https://github.com/4kd/realtime/issues/1

Seriously, try running it yourself:

```sh
git clone git@github.com:supabase/realtime.git && cd realtime
mix setup
```

```sh
** (Mix) Could not start application realtime: exited in: Realtime.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in String.split/3
            (elixir 1.14.1) lib/string.ex:479: String.split(nil, "-", [parts: 2])
            (realtime 2.1.1) lib/realtime/helpers.ex:100: Realtime.Helpers.short_node_id/0
            (realtime 2.1.1) lib/realtime/monitoring/prom_ex.ex:145: Realtime.PromEx.set_metrics_tags/0
            (realtime 2.1.1) lib/realtime/application.ex:33: Realtime.Application.start/2
            (kernel 8.5.1) application_master.erl:293: :application_master.start_it_old/4
```

_Obviously_ that doesn't work. Why would it be that easy/simple? 💭 
Reading the "Server Setup" section: https://github.com/supabase/realtime#server-setup 
I'm no closer to being up-and-running with this in _less_ than 5 minutes. 
It's just a malaise of poor documentation. 
We could fill-in the gaps in the docs but then we're just working for a [Venture-funded](https://techcrunch.com/2022/05/10/supabase-raises-80m-series-b-for-its-open-source-firebase-alternative) Startup for _Free_. 🤷‍♂️ 

> **Note**: `Realtime` server is tightly coupled to [Fly.io](https://fly.io/) at the moment.
<img width="976" alt="supabase-realtime-tightly-coupled-fly io" src="https://user-images.githubusercontent.com/194400/215975266-499e43d4-6a9b-4696-8359-921547de50cf.png">

i.e. they are using the infra that we are _already_ using. 
But adding a layer of their own on top so there's more latency. 
Why would we _want_ that? 🐌 
It's like taking a `wagyu` steak and mincing it up to make burgers! 🍔 
Why not just eat the _steak_!? 🥩 

The "**Pros**" are obvious; they're listed on the features/pricing pages. https://github.com/dwyl/technology-stack/issues/93#issuecomment-1407309340
I've tried to highlight the "***Cons***" above in my comments. 💬 


The _reason_ I _really_ wanted @LuchoTurtle to do a "**Speed Run**" 
(_and **`git push`** some code last **Friday**_ ⬆️ https://github.com/dwyl/technology-stack/issues/93#issuecomment-1406315952)
Was so that we could see how far a competent dev without any preconceived ideas and without _any_ distractions 
could get in a **_full_ day** of setting up `Flutter` with `Supabase`. 

Apparently, not very far ... https://github.com/dwyl/supabase-flutter-demo/issues/1#issuecomment-1407031410
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/194400/215740365-06f8f590-9e4d-4586-a192-cd2018c0ede8.png">

`if` someone without _any_ distractions/meetings can only manage an **`initial commit`** in **6 hours** 🧑‍💻 
the _extrapolation_ is that we will _never_ get anywhere with it ... ⏳ 
I know this can seem "_harsh_", but think about it from the perspective of someone paying by-the-hour ... 💸 

Imagine you ordered a pizza from a restaurant you know makes _superb_ pies ... 🍕 
You're patient but expect delivery in a _reasonable_ amount of time 🛵 
The time for the arrival of your delicious meal comes and goes ⌚ 👀 
What now? 💭 

I've spent _considerably_ more time deep-diving into `Supabase` than I wanted to right now.
I _really_ wanted someone `else` on the team to do a _deep_ analysis of the platform and present their findings.
I _still_ think it's promising but isn't yet a _flawless_ solution to our tech challenges.
A **`Firebase` Clone** with Open Source Tools is very much needed but it's still very much work-in-progress.
Respectfully, I feel they're going about it in _totally_ the wrong way by cobbling it together.

<img width="853" alt="image" src="https://user-images.githubusercontent.com/194400/215977746-a4262851-5359-498f-815d-ea78b378fcf7.png">

They _could_ have built the whole thing in `Phoenix` and it could run as a _single_ Fly.io instance.
`Supabase` does _not_ have _all_ the features we need, not even _close_. 

<img width="1108" alt="supabase-realtime-presence-beta" src="https://user-images.githubusercontent.com/194400/215978557-b0285396-a9e8-4f50-a0b5-96eefe920228.png">


**`if`** instead of wasting my time on this research I had invested it re-building **`Auth`** https://github.com/dwyl/auth/issues/207 
I'm 100% sure I would be **`done`** with the re-build by now. 
**`Auth v2`**  will be an Order of Magnitude simpler and easier to setup than **`Supabase`**. 
_Faster_ for both the Dev and the `person` _using_ it. 
_Easy_ to run on `localhost` with clear instructions.
But also _easy_ to ***not*** have to run on `localhost` and _complete_ separation of concerns
between storing **_personal_ data** and app-related data. The way it _should_ be done. 

I'm going to build it in the next week. (even though I have an up-coming family long-weekend away... ⏳ )
Meanwhile _please_ take a look at and give feedback on: https://github.com/dwyl/mvp/issues/140#issuecomment-1404371243

If @LuchoTurtle and @SimonLab can _focus_ on the front-end for the next week I can re-build `Auth`. 
Start by updating the code in `MVP` to match the `Figma` layout/wireframe. 
I _use_ the `MVP` multiple times a day and it frustrates me _every_ time! https://github.com/dwyl/mvp/issues/221#issuecomment-1332398701

**Comment by iteles** [comment]
Purely from this analysis it seems pretty obvious that Supabase isn't ready for us to use. 
Thanks for carrying out the research @nelsonic. I feel like this didn't have to be done by you  but maybe we can extrapolate a set of questions to be answered as a framework for this kind of research into whether a new technology should be used?

We also can't lose sight of the fact that this is an MVP - although we need to build a solid foundation, we also need to get it Done because every hour is coming out of our own pockets. If what we are already using is actually a better fit for our needs, that should be obvious after a 1 day spike and we can move on 👌🏻

**Comment by nelsonic** [comment]
@iteles the "framework" for proposing new tech has existed for *years*: https://github.com/dwyl/technology-stack/issues/18
The whole point of the **`SPIKE`** to investigate the viability of `Supabase` last week was to determine what it _could_ do for us. It can do what we _already_ have with `Phoenix`. It can do `Auth` _worse_ and with more setup steps than what we _already_ have. It does have a few other features that are nice-to-have like auto-generating API endpoints from database tables, but as we've seen from our API work: https://github.com/dwyl/mvp/issues/256 we don't actually _want_ a basic endpoint, rather we want a _complete_ query to return all related data similar to a `Graph` query, but without the unnecessary [[sloooooow](https://github.com/dwyl/learn-graphQL/issues/23)] response time. We are at the stage where we can _hand-craft_ our API for _speed_. We want to give the `people` using our `App` the _fastest_ experience possible. We will not achieve that with a generic one-size-fits-all solution. We need to be _focussed_ on building something that fits our needs _exactly_, not trying to shoe-horn `Supabase` into our stack because it has a cool-sounding name.

I _agree_ with @SimonLab that we could get up-and-running faster with `Supabase` in the _short_ run ... 🚀 
But then we would _very_ quickly hit a brick wall in terms of our engineering velocity and specifically DevOps.
The _features_ we _need_ are incomplete in `Supabase` and the ones we _don't_ need are a distraction.

**Comment by nelsonic** [comment]
@rubensdemelo excellent question. Thanks very much for asking it! 🎉 
I've added it to my/our list to answer it: https://github.com/dwyl/product-roadmap/issues/45 👌 
Meanwhile, how did you discover this thread?! 🔍 😊

**Comment by rubensdemelo** [comment]
@nelsonic sorry for late reply. 

I discovered this repo [technology-stack](https://github.com/dwyl/technology-stack)  from some a search about offline first mobile app. 

I also explored some topics and read about elixir/phoenix.

Finally, I found some topics releated with flutter and then dive in.

**Comment by nelsonic** [comment]
Top of HN this morning: 
https://news.ycombinator.com/item?id=36004925

Migrating from Supabase
https://blog.val.town/blog/migrating-from-supabase
